version: '3'
services:
  irpf:
    container_name: irpf2021
    build: .
    working_dir: /opt/IRPF2021
    environment:
      - DISPLAY=${DISPLAY}
      - _JAVA_OPTIONS='-Dawt.useSystemAAFontSettings=on'
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ~/Documents/IRPF/2021:/home/irpf/ProgramasRFB
